uploads = []
outputs = []

[[generated]]
id = "FoGJKaGZI9vwJomUTYK6x"
uri = "file://artifacts/axstudio/public/hero-bg.png"
type = "image"
title = "Joseon era kids playing boardgame"

[[generated]]
id = "a0ZXSKRcPZi616Vus062N"
uri = "file://artifacts/axstudio/public/game-bg.png"
type = "image"
title = "Ancient Seunggyeongdo board game"

[[generated]]
id = "L2s180gWpoLEl8eW69szU"
uri = "file://artifacts/axstudio/public/project-bg.png"
type = "image"
title = "Kids traveling time in Joseon"

[[generated]]
id = "3sAFZDseNnhYSIISxb_xa"
uri = "file://attached_assets/generated_images/two_modern_korean_middle_eb31.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Pw2i7_jeMmhEpYOWnoObA"
uri = "file://attached_assets/generated_images/a_swirling_cosmic_time_04e2.png"
type = "image"
title = "generated_image"
